apiversion: v1
kind: Service
metadata:
  name: tic-tac-toe
  labels:
    app: tic-tac-toe
spec:
  type: ClusterIP
    selector:
      app: tic-tac-toe
      ports:
        - containerPort: 80
          Port: 80
